import { randomUUID } from "node:crypto";
import { existsSync, mkdtempSync, readdirSync, rmSync, statSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { ensureConvertxCopy } from "../src/bun/bundle";
import { buildConvertxEnv, converterPathEntries, startConvertX } from "../src/bun/convertx";
import { waitForHealth } from "../src/bun/health";
import { getAppPaths } from "../src/bun/paths";
import { findFreePort } from "../src/bun/port";

const PROJECT_ROOT = import.meta.dir.replace(/[\\/]scripts$/, "");
const VENDOR_CONVERTX = join(PROJECT_ROOT, "vendor", "convertx");
const CONVERTERS_DIR = join(PROJECT_ROOT, "vendor", "converters", "win");

// A minimal valid 2x2 PNG, generated by ImageMagick so the bundled converter
// accepts it (a hand-rolled/truncated PNG gets rejected as "not enough image data").
const TEST_PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAAAIAAAACAQAAAABazTCJAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAACYktHRAAB3YoTpAAAAAd0SU1FB+oFEhYUIESQqn8AAAAldEVYdGRhdGU6Y3JlYXRlADIwMjYtMDUtMThUMjI6MjA6MzIrMDA6MDB0HDspAAAAJXRFWHRkYXRlOm1vZGlmeQAyMDI2LTA1LTE4VDIyOjIwOjMyKzAwOjAwBUGDlQAAACh0RVh0ZGF0ZTp0aW1lc3RhbXAAMjAyNi0wNS0xOFQyMjoyMDozMiswMDowMFJUokoAAAAMSURBVAjXYzjAcAAAAwQBgcU7oqkAAAAASUVORK5CYII=";

/** Parse a cookie value out of a set-cookie header list. */
function cookieValue(setCookies: string[], name: string): string {
  for (const sc of setCookies) {
    const match = sc.match(new RegExp(`^${name}=([^;]*)`));
    if (match) return match[1]!;
  }
  throw new Error(`Cookie '${name}' was not set by ConvertX`);
}

/**
 * Delete the temp app-data dir. The just-killed ConvertX child may briefly
 * hold file locks (SQLite db, uploads) on Windows, so retry a few times
 * before giving up — a leftover temp dir is reported, never fatal.
 */
async function removeTempDir(dir: string): Promise<void> {
  for (let attempt = 1; attempt <= 5; attempt++) {
    try {
      rmSync(dir, { recursive: true, force: true });
      return;
    } catch {
      if (attempt === 5) {
        console.error(`Warning: could not remove temp dir, left behind: ${dir}`);
        return;
      }
      await Bun.sleep(500);
    }
  }
}

async function main(): Promise<void> {
  if (!existsSync(join(VENDOR_CONVERTX, "package.json"))) {
    throw new Error("ConvertX not vendored — run scripts/setup-convertx.ts first.");
  }

  // Run against a throwaway app-data dir: the default base is the REAL
  // %APPDATA% profile, where ensureConvertxCopy would no-op onto a stale copy
  // and the test would write into the production SQLite DB. A fresh copy of
  // vendor/convertx per run is the accepted cost — correctness over speed.
  const appDataBase = mkdtempSync(join(tmpdir(), "cx-smoke-"));
  console.log(`Using temp app-data base: ${appDataBase}`);

  // The try opens right after mkdtempSync: the vendor copy and port allocation
  // below can throw, and the finally must still remove the temp dir (including
  // a large half-written convertx.partial).
  let proc: { stop: () => void } | undefined;
  try {
    const paths = getAppPaths(appDataBase);
    ensureConvertxCopy(VENDOR_CONVERTX, paths.convertxDir);
    const port = await findFreePort();
    const base = `http://127.0.0.1:${port}`;

    const env = buildConvertxEnv({
      port,
      jwtSecret: randomUUID(),
      pathPrepend: converterPathEntries(CONVERTERS_DIR),
    });
    proc = startConvertX({
      bunPath: process.execPath,
      convertxDir: paths.convertxDir,
      env,
      onStderr: (c) => process.stderr.write(`[convertx] ${c}`),
    });

    await waitForHealth(`${base}/`, 45_000);

    // 1. GET / -> ConvertX mints the auth + jobId cookies (no login screen).
    const root = await fetch(`${base}/`, { redirect: "manual" });
    if (root.status !== 200) {
      throw new Error(`GET / returned ${root.status}, expected 200 (no-login mode)`);
    }
    const setCookies = root.headers.getSetCookie();
    const auth = cookieValue(setCookies, "auth");
    const jobId = cookieValue(setCookies, "jobId");
    const cookie = `auth=${auth}; jobId=${jobId}`;
    console.log(`Session established (jobId=${jobId}).`);

    // 2. POST /upload — send a 2x2 PNG.
    const png = Buffer.from(TEST_PNG_BASE64, "base64");
    const uploadForm = new FormData();
    uploadForm.append("file", new File([png], "test.png", { type: "image/png" }));
    const upload = await fetch(`${base}/upload`, {
      method: "POST",
      headers: { cookie },
      body: uploadForm,
    });
    if (!upload.ok) throw new Error(`POST /upload returned ${upload.status}`);
    console.log("Uploaded test.png.");

    // 3. POST /convert — PNG -> JPG via ImageMagick (runs in the background).
    const convertForm = new FormData();
    convertForm.append("convert_to", "jpg,imagemagick");
    convertForm.append("file_names", JSON.stringify(["test.png"]));
    const convert = await fetch(`${base}/convert`, {
      method: "POST",
      headers: { cookie },
      body: convertForm,
      redirect: "manual",
    });
    if (convert.status !== 302) {
      throw new Error(`POST /convert returned ${convert.status}, expected 302`);
    }
    console.log("Conversion requested.");

    // 4. Poll the output directory (UNAUTHENTICATED_USER_SHARING -> user id 0).
    //    Match any non-empty file — ConvertX may name it test.jpg or test.jpeg.
    const outDir = join(paths.convertxDir, "data", "output", "0", jobId);
    const deadline = Date.now() + 30_000;
    while (Date.now() < deadline) {
      if (existsSync(outDir)) {
        const produced = readdirSync(outDir).filter((name) => {
          const s = statSync(join(outDir, name));
          return s.isFile() && s.size > 0;
        });
        if (produced.length > 0) {
          console.log(`\nSMOKE TEST PASSED — produced ${join(outDir, produced[0]!)}`);
          return;
        }
      }
      await Bun.sleep(300);
    }
    throw new Error(`Timed out waiting for output in: ${outDir}`);
  } finally {
    proc?.stop();
    await removeTempDir(appDataBase);
  }
}

main().catch((err) => {
  console.error(`\nSMOKE TEST FAILED: ${err instanceof Error ? err.message : err}`);
  process.exit(1);
});
